#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_DEFAULT_OUTPUT_VOLUME 100

#define AUDIO_I2S_METHOD_SIMPLEX

// INMP441
#define AUDIO_I2S_MIC_GPIO_SCK   GPIO_NUM_32
#define AUDIO_I2S_MIC_GPIO_WS    GPIO_NUM_33
#define AUDIO_I2S_MIC_GPIO_DIN   GPIO_NUM_34

// MAX98357A
#define AUDIO_I2S_SPK_GPIO_BCLK  GPIO_NUM_26
#define AUDIO_I2S_SPK_GPIO_LRCK  GPIO_NUM_27
#define AUDIO_I2S_SPK_GPIO_DOUT  GPIO_NUM_25

#define BOOT_BUTTON_GPIO         GPIO_NUM_0
#define BUILTIN_LED_GPIO         GPIO_NUM_2
#define EXTERNAL_RGB_LED_GPIO    GPIO_NUM_4

#define LOCAL_XIAOZHI_WS_URL     "ws://192.168.1.132:8000/xiaozhi/v1/"
#define LOCAL_XIAOZHI_WS_VERSION 1
#define LOCAL_XIAOZHI_OTA_URL    "http://192.168.1.132:8002/xiaozhi/ota/"

#endif // _BOARD_CONFIG_H_
